#!/bin/bash

print_wifi() {
    ip=$(ip route get 8.8.8.8 2>/dev/null|grep -Eo 'src [0-9.]+'|grep -Eo '[0-9.]+')

    #if hash iw
    #then
        #wifi=$(iw wlp4s0 link | grep SSID | sed 's,.*SSID: ,,')
        #connectedto=$(iw wlp4s0 link | grep Connected | awk '{print $3}' | cut -c 10-)
    #fi

    echo -e "$wifi $connectedto $ip"
}

print_mem(){
	memfree=$(($(grep -m1 'MemAvailable:' /proc/meminfo | awk '{print $2}') / 1024))
	echo -e "$memfree"
}

print_temp(){
	test -f /sys/class/thermal/thermal_zone0/temp || return 0
	echo $(head -c 2 /sys/class/thermal/thermal_zone0/temp)C
}

print_bat(){
    $(acpi -v)
}

print_date(){
	date "+%a %m-%d %T%:::z"
}

while true
do

	# Get new transmitted, received byte number values and current time
	#get_bytes

	# Calculates speeds
	#vel_recv=$(get_velocity $received_bytes $old_received_bytes $now)
	#vel_trans=$(get_velocity $transmitted_bytes $old_transmitted_bytes $now)

	xsetroot -name "$(print_mem) $vel_recv $vel_trans $(print_temp) $(print_wifi) $(print_bat) $(test -f /tmp/r2d2 && cat /tmp/r2d2) $(print_date)"

	# Update old values to perform new calculations
	old_received_bytes=$received_bytes
	old_transmitted_bytes=$transmitted_bytes
	old_time=$now

	sleep 1

done
